-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM AUTHOR A
JOIN (SELECT BOOK_ID, PUBLISHED_DATE, AUTHOR_ID FROM BOOK
     WHERE CATEGORY LIKE '경제') B on
     A.AUTHOR_ID = B.AUTHOR_ID
 ORDER By B.PUBLISHED_DATE